# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: few_shots_clf workflow

env:
  PYPI_USER: ${{ secrets.PYPI_USER }}
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.6
        run: |
          sudo apt update
          sudo apt install python3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install package
        run: |
          python setup.py build
          python setup.py install

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lint with pylint
        run: |
          pylint --rcfile=.pylintrc few_shots_clf/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test with pytest
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Remmove old dist
        run: |
          [ -d dist ] && rm -rf dist
      - name: Build package
        run: |
          python setup.py check sdist
      - name: Check package
        run: |
          twine check dist/*
      - name: Deploy package to pypi
        run: |
          twine upload --repository-url https://upload.pypi.org/legacy/ -u $PYPI_USER -p $PYPI_PASSWORD dist/*
