# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: few-shots-clf workflow

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-dev.txt
          pip install -r requirements/requirements-docs.txt
          pip install tensorflow==2.4.1
      - name: Install package
        run: |
          python setup.py build
          python setup.py install
  lint:
    needs: build
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-dev.txt
          pip install -r requirements/requirements-docs.txt
          pip install tensorflow==2.4.1
          pip install .
      - name: Install pylint
        run: |
          sudo pip install pylint
      - name: Lint with pylint
        run: |
          pylint --rcfile=.pylintrc few_shots_clf/
  test:
    needs: build
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-dev.txt
          pip install -r requirements/requirements-docs.txt
          pip install tensorflow==2.4.1
          pip install .
      - name: Install pytest
        run: |
          sudo pip install pytest
      - name: Test with pytest
        run: |
          pytest
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    name: deploy
    env:
      TWINE_USERNAME: ${{ secrets.PYPI_USER }}
      TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-dev.txt
          pip install -r requirements/requirements-docs.txt
          pip install .
          pip install tensorflow==2.4.1
      - name: Install twine & setuptools
        run: |
          pip install twine setuptools
      - name: Build package
        run: |
          python setup.py check sdist
      - name: Check package
        run: |
          twine check dist/*
      - name: Deploy package to pypi
        run: |
          twine upload dist/*
